title: "bug"
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        ## Steps to reproduce the bug
  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: Steps to reproduce the bug (P.E. Go to... Click on... Scroll down to... Check error...)
      value: |
        ...
      render: bash
    validations:
      required: true
  - type: checkboxes
    id: device
    attributes:
      label: Which device are you using
      description: Please select the device in which you found a bug
      options:
      - label: Desktop Windows
      - label: Desktop MacOS
      - label: Desktop Linux
      - label: Mobile browser
      - label: App
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: (if aplicable) In which browsers are you seeing the problem?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Other
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: (if aplicable) What version of the browser are you using?
      description: Browser version
    validations:
      required: false
  - type: dropdown
    id: mobile-device
    attributes:
      label: (if aplicable) What mobile OS device are you using?
      multiple: false
      options:
        - iOS
        - Android
        - Other
    validations:
      required: false
  - type: input
    id: device-type
    attributes:
      label: (if aplicable) Which mobile devices are you using?
      description: P.E iPhone14, Google Pixel 5, Motorola Razr...
    validations:
      required: false
  - type: input
    id: device-version
    attributes:
      label: (if aplicable) Which version of the device OS are you running?
      description: P.E. iOS13, Android9...
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: In which page do you see the problem?
      description: Paste the url here
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: |
        Anything you want to add about the bug you are encountering
      
        Tip: You can also add images bu clicking here and the dragging files in!
      value: |
        ...  
      render: bash
    validations:
      required: false
