on:
  issues:
    types: [opened]
  discussion:
    types: [created]  

jobs:
  dupliket:
    runs-on: ubuntu-latest
    steps:
      - name: Find possible duplicates
        uses: Namchee/dupliket@v1.0.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}
          api_key: ${{ secrets.oAI_TOKEN }}
          label: duplicated
